events {
    worker_connections 1024;
}

http {
    include       mime.types;
    default_type  application/octet-stream;

    error_log  /var/log/nginx/error.log warn;
    access_log /var/log/nginx/access.log;

    server {
        listen 80;
        server_name localhost;

        location / {
            root /usr/share/nginx/html;
            index index.html index.htm;
            try_files $uri $uri/ /index.html;
        }

        location /api/ {
            # 'backend-app' là tên service trong docker-compose.yml
            # Cổng 8080 là cổng Spring Boot bên trong container
            proxy_pass http://backend-app:8080;

            # Các header bắt buộc
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
}